### ISSUE TITLE
qs v6.0.0 breaks cpanel-lib

### ISSUE THREAD

**Issue by ryansouthern** [vially/cpanel-lib#4]
```
node_modules/cpanel-lib/node_modules/qs/lib/index.js:5
const Stringify = require('./stringify');
^^^^^
SyntaxError: Use of const in strict mode.
    at Module._compile (module.js:439:25)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/node_modules/cpanel-lib/lib/cpanel.js:1:72)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
```

**Comment by vially** [comment]
Seems to be an issue with [qs](https://github.com/hapijs/qs/issues?utf8=%E2%9C%93&q=Use+of+const+in+strict+mode).

It seems that [qs now requires node 4.0.0](https://github.com/hapijs/qs/issues/131#issuecomment-153815999), so you'll have to either upgrade node or downgrade qs.
